import json
from pathlib import Path

from fastapi import APIRouter, HTTPException, Response

router = APIRouter(prefix="/evaluations", tags=["evaluations"])

_REPORT_PATH = Path("benchmarks/results/latest.json")


@router.get("/latest")
async def latest_benchmark_report() -> Response:
    """Serves the committed baseline-vs-agentic benchmark report (spec
    §33/§34, generated by `benchmarks/run_evaluation.py`) as-is — a real
    report from a real run, not data shaped for this endpoint."""
    if not _REPORT_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="No benchmark report found. Run `python benchmarks/run_evaluation.py` first.",
        )
    return Response(content=_REPORT_PATH.read_text(encoding="utf-8"), media_type="application/json")


@router.get("/latest/summary")
async def latest_benchmark_summary() -> dict[str, object]:
    if not _REPORT_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail="No benchmark report found. Run `python benchmarks/run_evaluation.py` first.",
        )
    data = json.loads(_REPORT_PATH.read_text(encoding="utf-8"))
    return {
        "generated_at": data["generated_at"],
        "embedding_provider": data["embedding_provider"],
        "llm_provider": data["llm_provider"],
        "baseline_summary": data["baseline_summary"],
        "agentic_summary": data["agentic_summary"],
        "case_count": len(data["cases"]),
    }
