"""initial schema

Revision ID: 77d4e3cf344b
Revises: 
Create Date: 2026-09-03 13:12:34.403811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '77d4e3cf344b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required by document_chunks.embedding (pgvector column) and its HNSW index
    # below. Idempotent so this migration is safe to run against a fresh
    # docker-compose database as well as the manually-provisioned local one.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('retrieval_config', sa.JSON(), nullable=False),
    sa.Column('embedding_config', sa.JSON(), nullable=False),
    sa.Column('source_authority_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('evaluation_datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index('ix_documents_collection_id', 'documents', ['collection_id'], unique=False)
    op.create_table('evaluation_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('expected_answer', sa.String(), nullable=True),
    sa.Column('expected_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('parent_query_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['parent_query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_trace_id'), 'queries', ['trace_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('chunking_config', sa.JSON(), nullable=False),
    sa.Column('embedding_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_results_case_id', 'evaluation_results', ['case_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_query_id', 'events', ['query_id'], unique=False)
    op.create_index(op.f('ix_events_trace_id'), 'events', ['trace_id'], unique=False)
    op.create_table('query_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('expand_query', sa.Boolean(), nullable=False),
    sa.Column('decompose', sa.Boolean(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('subqueries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('retrieval_strategy', sa.String(), nullable=False),
    sa.Column('query_text_used', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_runs_query_id', 'retrieval_runs', ['query_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parent_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_version_id', 'document_chunks', ['document_version_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('retrieval_run_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('sufficiency_judgement', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_items_query_id', 'evidence_items', ['query_id'], unique=False)
    op.create_table('retrieved_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('retrieval_run_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('dense_score', sa.Float(), nullable=True),
    sa.Column('sparse_score', sa.Float(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('selected_as_evidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['retrieval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieved_chunks_retrieval_run_id', 'retrieved_chunks', ['retrieval_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retrieved_chunks_retrieval_run_id', table_name='retrieved_chunks')
    op.drop_table('retrieved_chunks')
    op.drop_index('ix_evidence_items_query_id', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_table('citations')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_version_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_retrieval_runs_query_id', table_name='retrieval_runs')
    op.drop_table('retrieval_runs')
    op.drop_table('query_plans')
    op.drop_index(op.f('ix_events_trace_id'), table_name='events')
    op.drop_index('ix_events_query_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_evaluation_results_case_id', table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_table('document_versions')
    op.drop_table('answers')
    op.drop_index(op.f('ix_queries_trace_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_table('evaluation_cases')
    op.drop_index('ix_documents_collection_id', table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('evaluation_datasets')
    op.drop_table('collections')
    # ### end Alembic commands ###
