"""add content full text search

Revision ID: 938c2d23d9a7
Revises: 77d4e3cf344b
Create Date: 2026-09-03 15:04:49.030698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938c2d23d9a7'
down_revision: Union[str, Sequence[str], None] = '77d4e3cf344b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written rather than autogenerated: Alembic's autogenerate does not
    # reliably reproduce PostgreSQL's GENERATED ALWAYS AS ... STORED syntax
    # for computed columns, so this is written directly against the ORM
    # declaration in storage/models.py::DocumentChunk.content_tsv.
    op.execute(
        "ALTER TABLE document_chunks "
        "ADD COLUMN content_tsv tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', content)) STORED"
    )
    op.execute(
        "CREATE INDEX ix_document_chunks_content_tsv "
        "ON document_chunks USING gin (content_tsv)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_content_tsv")
    op.execute("ALTER TABLE document_chunks DROP COLUMN IF EXISTS content_tsv")
