"""add document_date to documents

Revision ID: ad0d105f4e90
Revises: ca20cbe7a367
Create Date: 2026-09-04 14:35:41.461673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0d105f4e90'
down_revision: Union[str, Sequence[str], None] = 'ca20cbe7a367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_date')
    # ### end Alembic commands ###
