"""add check constraints on document_type and document_version status

Revision ID: c969f8d87cbb
Revises: ad0d105f4e90
Create Date: 2026-09-04 15:16:28.144351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c969f8d87cbb'
down_revision: Union[str, Sequence[str], None] = 'ad0d105f4e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_document_versions_status', 'document_versions', "status IN ('pending','parsed','indexed')")
    op.create_check_constraint('ck_documents_document_type', 'documents', "document_type IN ('pdf','docx','txt','markdown','html','csv','json')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_documents_document_type', 'documents', type_='check')
    op.drop_constraint('ck_document_versions_status', 'document_versions', type_='check')
    # ### end Alembic commands ###
