"""add uniqueness constraints on document_chunks and retrieved_chunks

Revision ID: ca20cbe7a367
Revises: 938c2d23d9a7
Create Date: 2026-09-04 13:48:56.631380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca20cbe7a367'
down_revision: Union[str, Sequence[str], None] = '938c2d23d9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunks_version_index', 'document_chunks', ['document_version_id', 'chunk_index'])
    op.create_unique_constraint('uq_retrieved_chunks_run_chunk', 'retrieved_chunks', ['retrieval_run_id', 'chunk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_retrieved_chunks_run_chunk', 'retrieved_chunks', type_='unique')
    op.drop_constraint('uq_document_chunks_version_index', 'document_chunks', type_='unique')
    # ### end Alembic commands ###
